# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='incomplete',
            field=models.BooleanField(default=False),
        ),
    ]
