# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='interested_users',
        ),
    ]
