# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 08:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_remove_events_interested_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='interested_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
