# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_events_interested_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='event',
        ),
    ]
