# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170618_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='interested_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
