# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170619_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
