# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 04:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170823_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_by_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
