# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spark',
            name='spark_info',
            field=models.TextField(default=''),
        ),
    ]
