# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparks', '0002_spark_spark_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='spark',
            name='spark_organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='spark',
            name='spark_info',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AddField(
            model_name='spark',
            name='tags',
            field=models.ManyToManyField(blank=True, to='sparks.Tag'),
        ),
    ]
