# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparks', '0003_auto_20170601_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RenameField(
            model_name='spark',
            old_name='tags',
            new_name='interests',
        ),
    ]
