# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparks', '0004_auto_20170601_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spark',
            old_name='spark_name',
            new_name='spark_full_name',
        ),
    ]
