# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparks', '0005_auto_20170601_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spark',
            old_name='spark_full_name',
            new_name='spark_name',
        ),
    ]
