# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparks', '0006_auto_20170601_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='spark',
            name='tags',
            field=models.ManyToManyField(blank=True, to='sparks.Tag'),
        ),
        migrations.RemoveField(
            model_name='spark',
            name='interests',
        ),
        migrations.AddField(
            model_name='spark',
            name='interests',
            field=models.CharField(choices=[('AL', 'All'), ('ML', 'Malnutrition'), ('ED', 'Education'), ('PV', 'Poverty'), ('SW', 'Social Welfare'), ('HS', 'Hygiene and Sanitation')], default='AL', max_length=2),
        ),
    ]
