# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparks', '0007_auto_20170602_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='spark',
            name='gender',
            field=models.CharField(choices=[('N', 'None'), ('M', 'Male'), ('F', 'Female')], default='N', max_length=1),
        ),
    ]
