# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparks', '0009_auto_20170602_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spark',
            old_name='spark_full_name',
            new_name='spark_name',
        ),
    ]
