# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparks', '0010_auto_20170602_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='spark',
            name='award_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='spark',
            name='award_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='spark',
            name='award_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spark',
            name='award_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spark',
            name='award_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spark',
            name='contri_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='spark',
            name='contri_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='spark',
            name='contri_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spark',
            name='contri_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spark',
            name='contri_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spark',
            name='hobby1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='spark',
            name='idea_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='spark',
            name='idea_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='spark',
            name='idea_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spark',
            name='idea_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spark',
            name='idea_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spark',
            name='image',
            field=models.ImageField(blank=True, upload_to='sparks'),
        ),
    ]
