# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparks', '0012_auto_20170609_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spark',
            name='image',
            field=models.ImageField(blank=True, default='accounts/m-user.png', upload_to='sparks'),
        ),
    ]
