# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparks', '0019_spark_spark_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spark',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='spark',
            name='image',
        ),
        migrations.RemoveField(
            model_name='spark',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='spark',
            name='spark_city',
        ),
        migrations.RemoveField(
            model_name='spark',
            name='spark_locality',
        ),
        migrations.RemoveField(
            model_name='spark',
            name='spark_mail',
        ),
        migrations.RemoveField(
            model_name='spark',
            name='spark_name',
        ),
    ]
