# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='locality',
            field=models.CharField(default='', max_length=100),
        ),
    ]
