# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_locality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='back_image',
            field=models.ImageField(blank=True, upload_to='back_image'),
        ),
    ]
