# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170616_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_interests',
            field=models.CharField(choices=[('All', 'All'), ('Malnutrition', 'Malnutrition'), ('Education', 'Education'), ('Poverty', 'Poverty'), ('Social Welfare', 'Social Welfare'), ('Hygiene and Sanitation', 'Hygiene and Sanitation')], default='All', max_length=25),
        ),
    ]
